#' Make a ggplot2 model diagram.
#'
#' @description
#' `make_diagram()` generates a **ggplot2** object based on the data frames
#'     made with \code{\link{prepare_diagram}} and, optionally, updated with
#'     \code{\link{update_diagram}}.
#'
#' @param diagram_list A required list of data frames returned from the
#'     \code{\link{prepare_diagram}} function and, optionally, updated with
#'     \code{\link{update_diagram}}. See those functions for details
#'     about this object.
#' @param with_grid A logical indicating whether to return the ggplot
#'     with a grid. Default is FALSE. The grid can be helpful if you
#'     want/need to move items around.
#'
#' @return A ggplot2 object.
#'
#' @details This function uses all the information in the data frames list
#'    generated by \code{\link{prepare_diagram}} and, optionally, updated with
#'    \code{\link{update_diagram}} to make a `ggplot2` object. All location
#'    information and aesthetics are assumed fixed at this point -- no updates
#'    are made within this function. The underlying `ggplot2` code can be
#'    viewed in the \code{get_code} function, e.g.: type \code{get_code} with
#'    no parentheses in the R console.
#'
#' @examples
#' mymodel = list(variables = c("S","I","R"),
#'                flows = list(S_flows = c("-b*S*I"),
#'                             I_flows = c("b*S*I","-g*I"),
#'                             R_flows = c("g*I") ) )
#' diagram_list <- prepare_diagram(model_list = mymodel)
#'
#' # make diagram without grid
#' diagram <- make_diagram(diagram_list)
#'
#' # make diagram with grid
#' diagram_with_grid <- make_diagram(diagram_list, with_grid = TRUE)
#'
#' @import ggplot2
#' @export
#'

make_diagram <- function (diagram_list, with_grid = FALSE) {

  # check input data frames for conformity
  test <- check_dataframes(diagram_list)
  if(!is.null(test)) {
    stop(test)
  }

  # unlist the data frames to objects
  variables <- diagram_list$variables
  flows <- diagram_list$flows

  # evaluate the ggplot2 code using current environment args
  theplot <- eval(parse(text = get_code()))

  return(theplot)
}
